[theme]
# The primary accent color for widgets
primaryColor = "#0f0f59"

# The main background color
backgroundColor = "#f0e9e3"

# Color for sidebars and input widgets
secondaryBackgroundColor = "#f0e9e3"

# Color for text
textColor = "#262730"

# Font style
font = "monospace"
